#!/usr/bin/env bash

_setup_aliases() {
  alias_available() {
    local target="$1"
    shift

    for alternative in "$@"; do
      if exists "$alternative"; then
        alias "$target"="$alternative"
        return 0
      fi
    done

    return 1
  }

  alias cp="cp --interactive --verbose --recursive"
  alias hs="history | grep --color=auto"
  alias ls="ls --color=auto"
  alias mkdir="mkdir --verbose --parents"
  alias mv="mv --interactive --verbose"
  alias scp='rsync --archive --verbose --human-readable --compress --partial --progress --xattrs --acls --rsh="ssh"'

  if [ "$(uname)" = "Linux" ]; then
    alias logout='loginctl terminate-session "$XDG_SESSION_ID"'
  fi

  if alias_available cat bat; then
    if ! alias_available man batman; then
      export MANPAGER="sh -c 'col -bx | bat --language man --plain --pager=\"less --raw-control-chars\"'"
      export MANROFFOPT="-c"
    fi

    alias_available rg batgrep
  fi

  alias_available curl curlie http
  alias_available dig doggo
  alias_available watch hwatch
  alias_available less ov
  alias_available ping prettyping
  alias_available ps procs
  alias_available top btm htop

}

_setup_aliases
unset -f _setup_aliases
